FROM jamieiles/oldland-toolchain:latest
MAINTAINER Jamie Iles <jamie@jamieiles.com>
RUN apt-get update
RUN apt-get install -y cmake verilator iverilog python-junitxml python-yaml python-pip libusb-1.0-0-dev liblua5.2-dev device-tree-compiler
RUN pip install junit_xml termcolor
